/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_)

Copyright 2008 SciberQuest Inc.

*/
#ifndef pqSQFieldTracer_h
#define pqSQFieldTracer_h

#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"


class pqSQFieldTracer : public pqAutoGeneratedObjectPanel
{
Q_OBJECT
public:
  pqSQFieldTracer( pqProxy *pxy, QWidget *p ) ; 
  ~pqSQFieldTracer() {} ;
};

#endif
