#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"

#include <QLabel>
#include <QComboBox>
#include <QLayout>

#include "pqPropertyManager.h"
#include "pqNamedWidgets.h"

class pqSQFieldTracerPanel : public pqAutoGeneratedObjectPanel
{
Q_OBJECT
 public:
  pqSQFieldTracerPanel( pqProxy *pxy, QWidget *p ) ; 
  ~pqSQFieldTracerPanel() {} ;
};

//  : pqAutoGeneratedObjectPanel( pxy , p ) {} 
//   {
//     QWidget *widget;
//     widget = this->findChild<QWidget*>("UseDynamicScheduler");
//     QWidget *tmpwidget1 = this->findChild<QWidget*>("MasterBlockSize");
//     QWidget *tmpwidget2 = this->findChild<QWidget*>("WorkerBlockSize");
//     // cout << "Setting up the DynamicScheduler" << endl; 
//     tmpwidget1->setEnabled(false);
//     tmpwidget2->setEnabled(false);
//     connect(widget, 
//             SIGNAL(clicked(bool)), 
//             tmpwidget1, 
//             SLOT(setEnabled(bool)));
//     connect(widget,
//             SIGNAL(clicked(bool)),
//             tmpwidget2,
//             SLOT(setEnabled(bool)));
//   };
