#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"

#include <QLabel>
#include <QComboBox>
#include <QLayout>

#include "pqPropertyManager.h"
#include "pqNamedWidgets.h"

class pqSQFieldTracerPanel : public pqAutoGeneratedObjectPanel
{
Q_OBJECT
 public:
  pqSQFieldTracerPanel( pqProxy *pxy, QWidget *p ) ; 
  ~pqSQFieldTracerPanel() {} ;
};

