/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_)

Copyright on 2008 SciberQuest Inc.
*/

#include "pqSQFieldTracer.h"

#include <iostream>
using std::cerr;
using std::endl;

//-----------------------------------------------------------------------------
pqSQFieldTracer::pqSQFieldTracer( 
      pqProxy* pxy, 
      QWidget* p ) 
             : 
  pqAutoGeneratedObjectPanel( pxy , p ) 
{
  #if defined pqSQFieldTracePanelDEBUG
  cerr << "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::accept" << endl;
  #endif

  QWidget *widget;
  widget = this->findChild<QWidget*>("UseDynamicScheduler");

  QWidget *masterBlock = this->findChild<QWidget*>("MasterBlockSize");
  QWidget *workerBlock = this->findChild<QWidget*>("WorkerBlockSize");

  masterBlock->setEnabled(false);
  workerBlock->setEnabled(false);

  connect(widget,
          SIGNAL(clicked(bool)), 
          masterBlock, 
          SLOT(setEnabled(bool)));
  connect(widget,
          SIGNAL(clicked(bool)),
          workerBlock,
          SLOT(setEnabled(bool)));
};
