//
// Extra items
//
//#include "pqNamedObjectPanel.h"
//#include "pqComponentsExport.h"// no comment


#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"

#include <QLabel>
#include <QComboBox>
#include <QLayout>

class pqSQFieldTracer  : public pqAutoGeneratedObjectPanel
{
Q_OBJECT
 public:
pqSQFieldTracer( pqProxy *pxy, QWidget *p ) : pqAutoGeneratedObjectPanel( pxy , p );
  ~pqSQFieldTracer();
}

//     // Widgets that were acidentally created
//     // Unlink them in the manager properties
//     QWidget *widget = this->findChild<QWidget*>("UseDynamicScheduler");
//     widget->hide();
