/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_)

Copyright on 2008 SciberQuest Inc.
*/

#include "pqSQFieldTracer.h"

#include <iostream>
using std::cerr;
using std::endl;

//-----------------------------------------------------------------------------
pqSQFieldTracer::pqSQFieldTracer( 
      pqProxy* pxy, 
      QWidget* p ) 
             : 
  pqAutoGeneratedObjectPanel( pxy , p ) 
{
#if defined pqSQFieldTracePanelDEBUG
  cerr << "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::accept" << endl;
#endif

  QWidget *widget;
  widget = this->findChild<QWidget*>("UseDynamicScheduler");

  QWidget *tmpwidget1 = this->findChild<QWidget*>("MasterBlockSize");
  QWidget *tmpwidget2 = this->findChild<QWidget*>("WorkerBlockSize");

  tmpwidget1->setEnabled(false);
  tmpwidget2->setEnabled(false);

  connect(widget, 
          SIGNAL(clicked(bool)), 
          tmpwidget1, 
          SLOT(setEnabled(bool)));
  connect(widget,
          SIGNAL(clicked(bool)),
          tmpwidget2,
          SLOT(setEnabled(bool)));
};
