/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_) 

Copyright 2008 SciberQuest Inc.

*/
#ifndef pqSQPlaneSource_h
#define pqSQPlaneSource_h

#include "pqNamedObjectPanel.h"
#include "pqComponentsExport.h"// no comment
#include <vtkstd/vector>// no comment

#include "ui_pqSQPlaneSourceForm.h"//  no comment
using Ui::pqSQPlaneSourceForm;

// Define the following to enable debug io
// #define pqSQPlaneSourceDEBUG

class pqProxy;
class vtkEventQtSlotConnect;
class QWidget;

class pqSQPlaneSource : public pqNamedObjectPanel
{
  Q_OBJECT
public:
  pqSQPlaneSource(pqProxy* proxy, QWidget* p = NULL);
  ~pqSQPlaneSource();


protected slots:
  // Description:
  // read state from disk.
  void Restore();
  // Description:
  // write state to disk.
  void Save();

  // Description:
  // check if cooridnates produce a good plane.
  int ValidateCoordinates();

  // Description:
  // calculate plane's dimensions for display.
  void CalculateDims();

  // Description:
  // calculate plane's grid spacing for display.
  void CalculateSpacing();

  // Description:
  // correct the aspect so that pixels are square if enabled,
  void CorrectAspect();

  // Description:
  // Update the UI with values from the server.
  void PullServerConfig();
  void PushServerConfig();
  // Description:
  // Update information events are generated by PV in many instances.
  // We need to watch for the ones coresponding to RequestInformation
  // on the server side where the new database view is stored in 
  // vtkInformation. This will take that information object
  // and load it in to the QTreeWidget.
  void UpdateInformationEvent();
  // Description:
  // This is where we have to communicate our state to the server.
  void accept();
  // Description:
  // Manipulate command which can be run using fork/exec.
  void ExecCommand();
  void AddCommand();
  void DelCommand();
  void EditCommand(bool state);

private:
  double dims[2];
  double dx[2];
  int nx[2];



private:
  pqSQPlaneSourceForm *Form;
  vtkEventQtSlotConnect *VTKConnect;
};

#endif
