#!/bin/bash

#  -DBoost_INCLUDE_DIR=\
#  -DPYTHON_EXECUTABLE=\
#  -DPYTHON_INCLUDE_DIR=\
#  -DPYTHON_LIBRARY=\
#  -DQT_QMAKE_EXECUTABLE=\
#  -DMPIEXEC=\
#  -DMPI_INCLUDE_PATH=\
#  -DMPI_LIBRARY=\
#  -DMPI_EXTRA_LIBRARY=\
#  -DPARAVIEW_INSTALL_MPIEXEC=ON \
#  -DCGNS_INCLUDE_DIR=\
#  -DGNS_LIBRARY=\
#  -DSILO_INCLUDE_DIR=\
#  -DSILO_LIBRARY=\


cmake \
  -DCMAKE_BUUILD_TYPE=Debug \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_TESTING=OFF \
  -DPARAVIEW_DISABLE_VTK_TESTING=ON \
  -DPARAVIEW_TESTING_WITH_PYTHON=OFF \
  -DVTK_USE_BOOST=ON \
  -DPARAVIEW_ENABLE_PYTHON=ON \
  -DPARAVIEW_USE_MPI=ON \
  -DPARAVIEW_BUILD_PLUGIN=EyeDomeLighting \
  -DPARAVIEW_USE_VISITBRIDGE=ON \
  -DVISIT_BUILD_READER_CGNS=OFF \
  -DVISIT_BUILD_READER_Silo=OFF \
  -DBUILD_DOCUMENTATION=ON \
  -DPARAVIEW_GENERATE_PROXY_DOCUMENTATION=ON \
  -DGENERATE_FILTERS_DOCUMENTATION=ON \
  -DDOCUMENTATION_HTML_HELP=ON \
  -DPARAVIEW_INSTALL_DEVELOPMENT=ON \
  $*
  
