/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_)

Copyright on 2008 SciberQuest Inc.
*/
#include "pqSC11DemoReader.h"

#include "SQMacros.h"

#include "pqApplicationCore.h"
#include "pqRenderView.h"
#include "pqActiveObjects.h"

#include "vtkSMProxy.h"
#include "vtkSMProperty.h"
#include "vtkSMIntVectorProperty.h"
#include "vtkSMDoubleVectorProperty.h"
#include "vtkSMRenderViewProxy.h"

#include <QWidget>
#include <QCheckBox>
#include <QSpinBox>
#include <QDoubleValidator>
#include <QLineEdit>
#include <QTimer>
#include <QLayout>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QDebug>
#include <QSettings>


#include <iostream>
using std::cerr;
using std::endl;

//#define pqSC11DemoReaderDEBUG


//-----------------------------------------------------------------------------
pqSC11DemoReader::pqSC11DemoReader(
      pqProxy* pxy,
      QWidget* p)
             :
  pqAutoGeneratedObjectPanel(pxy,p),
  RenderState(0),
  Frame(0)

{
  #if defined pqSC11DemoReaderDEBUG
  cerr << ":::::::::::::::::::::::::::::::pqSC11DemoReader" << endl;
  #endif

  //QVBoxLayout *vlayout=dynamic_cast<QVBoxLayout*>(this->layout());

  QVBoxLayout *vlayout=new QVBoxLayout;

  // toggle the demo
  this->RunButton=new QCheckBox("Run Demo", this);
  QObject::connect(
        this->RunButton,
        SIGNAL(toggled(bool)),
        this,
        SLOT(RunDemo(bool)));
  vlayout->addWidget(this->RunButton);

  QHBoxLayout *hlayout;
  QLabel *label;
  const int labelHSize=100;
  const int labelVSize=12;
  // still frames count
  hlayout=new QHBoxLayout;
  label=new QLabel("Timer Interval:");
  label->setMinimumSize(labelHSize,labelVSize);
  hlayout->addWidget(label);

  this->TimerInterval=new QSpinBox;
  this->TimerInterval->setMinimum(0);
  this->TimerInterval->setMaximum(100000);
  hlayout->addWidget(this->TimerInterval);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  // still frames count
  hlayout=new QHBoxLayout;
  label=new QLabel("Still Frames:");
  label->setMinimumSize(labelHSize,labelVSize);
  hlayout->addWidget(label);

  this->StillFrames=new QSpinBox;
  this->StillFrames->setMinimum(0);
  this->StillFrames->setMaximum(100000);
  hlayout->addWidget(this->StillFrames);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  // rotate frames count
  hlayout=new QHBoxLayout;
  hlayout=new QHBoxLayout;
  label=new QLabel("Rotate Frames:");
  label->setMinimumSize(labelHSize,labelVSize);
  hlayout->addWidget(label);

  this->RotateFrames=new QSpinBox;
  this->RotateFrames->setMinimum(0);
  this->RotateFrames->setMaximum(100000);
  hlayout->addWidget(this->RotateFrames);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  // camera radius
  hlayout=new QHBoxLayout;
  hlayout=new QHBoxLayout;
  label=new QLabel("Camera Radius:");
  label->setMinimumSize(labelHSize,labelVSize);
  hlayout->addWidget(label);

  this->CamRadius=new QLineEdit;
  this->CamRadius->setValidator(new QDoubleValidator(this->CamRadius));
  hlayout->addWidget(this->CamRadius);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  // camera radius
  hlayout=new QHBoxLayout;
  hlayout=new QHBoxLayout;
  label=new QLabel("Camera Height:");
  label->setMinimumSize(labelHSize,labelVSize);
  hlayout->addWidget(label);

  this->CamHeight=new QLineEdit;
  this->CamHeight->setValidator(new QDoubleValidator(this->CamHeight));
  hlayout->addWidget(this->CamHeight);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  // camera focal point
  hlayout=new QHBoxLayout;
  hlayout=new QHBoxLayout;
  label=new QLabel("Focal Point:");
  label->setMinimumSize(labelHSize,labelVSize);
  hlayout->addWidget(label);

  this->FocalX=new QLineEdit;
  this->FocalX->setValidator(new QDoubleValidator(this->FocalX));
  hlayout->addWidget(this->FocalX);

  this->FocalY=new QLineEdit;
  this->FocalY->setValidator(new QDoubleValidator(this->FocalY));
  hlayout->addWidget(this->FocalY);

  this->FocalZ=new QLineEdit;
  this->FocalZ->setValidator(new QDoubleValidator(this->FocalZ));
  hlayout->addWidget(this->FocalZ);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  // initialize button
  hlayout=new QHBoxLayout;
  QPushButton *initButton=new QPushButton("Initialize");
  QObject::connect(
        initButton,
        SIGNAL(released()),
        this,
        SLOT(Initialize()));
  hlayout->addWidget(initButton);
  hlayout->addStretch();

  vlayout->addLayout(hlayout);

  //
  QWidget *w=new QWidget(this);
  w->setLayout(vlayout);
  this->layout()->addWidget(w);
  // initialize from last used values
  this->Restore();
}

//-----------------------------------------------------------------------------
pqSC11DemoReader::~pqSC11DemoReader()
{
  this->Save();
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::Restore()
{
  QStringList defaults;
  defaults
       << "500"  // timer interval
       << "10"   // still frames
       << "100"  // rotate frames
       << "3000" // camera radius
       << "2000" // camera height
       << "511.5" << "511.5" << "0.0"; // focal point

  QSettings settings("LBNL","SC11Demo");

  QStringList defs=settings.value("SC11DemoReader/defaults",defaults).toStringList();

  this->TimerInterval->setValue(defs.at(0).toInt());
  this->StillFrames->setValue(defs.at(1).toInt());
  this->RotateFrames->setValue(defs.at(2).toInt());
  this->CamRadius->setText(defs.at(3));
  this->CamHeight->setText(defs.at(4));
  this->FocalX->setText(defs.at(5));
  this->FocalY->setText(defs.at(6));
  this->FocalZ->setText(defs.at(7));
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::Save()
{
  QStringList defs;

  defs
    << QString("%1").arg(this->TimerInterval->value())
    << QString("%1").arg(this->StillFrames->value())
    << QString("%1").arg(this->RotateFrames->value())
    << this->CamRadius->text()
    << this->CamHeight->text()
    << this->FocalX->text()
    << this->FocalY->text()
    << this->FocalZ->text();

  QSettings settings("LBNL","SC11Demo");
  settings.setValue("SC11DemoReader/defaults",defs);
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::Initialize()
{
  this->RenderState=RENDER_STILL;
  this->Frame=0;
  this->RotateRender();
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::RunDemo(bool start)
{
  #if defined pqSC11DemoReaderDEBUG
  cerr << ":::::::::::::::::::::::::::::::RunDemo" << endl;
  #endif

  if (start)
    {
    #if defined pqSC11DemoReaderDEBUG
    cerr << "starting" << endl;
    #endif
    this->UpdateReader();
    }
  else
    {
    #if defined pqSC11DemoReaderDEBUG
    cerr << "stopping" << endl;
    #endif
    }
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::UpdateReader()
{
  #if defined pqSC11DemoReaderDEBUG
  cerr << ":::::::::::::::::::::::::::::::UpdateReader" << endl;
  #endif

  // mark server side as dirty
  this->setModified();
  this->accept();

  // render
  size_t nFrames;
  switch (this->RenderState)
    {
    case RENDER_STILL:
      nFrames=this->StillFrames->text().toInt();
      if (this->Frame>nFrames)
        {
        this->RenderState=RENDER_ROTATE;
        this->Frame=0;
        }
      else
        {
        this->StillRender();
        this->Frame+=1;
        }
      break;

    case RENDER_ROTATE:
      nFrames=this->RotateFrames->text().toInt();
      if (this->Frame>nFrames)
        {
        this->RenderState=RENDER_STILL;
        this->Frame=0;
        }
      else
        {
        this->RotateRender();
        this->Frame+=1;
        }
      break;

    default:
      cerr << "Error, bas case " << this->RenderState << endl;
      this->RenderState=RENDER_STILL;
      this->Frame=0;
    }

  // reset timer
  if (this->RunButton->isChecked())
    {
    int interval=this->TimerInterval->value();
    QTimer::singleShot(interval, this, SLOT(UpdateReader()));
    }
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::StillRender()
{
  #if defined pqSC11DemoReaderDEBUG
  cerr << ":::::::::::::::::::::::::::::::StillRender" << endl;
  #endif

  pqRenderView* renderView =
    qobject_cast<pqRenderView*>(pqActiveObjects::instance().activeView());

  renderView->render();
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::RotateRender()
{
  #if defined pqSC11DemoReaderDEBUG
  cerr << ":::::::::::::::::::::::::::::::MotionRender" << endl;
  #endif

  double nFrames=this->RotateFrames->text().toDouble();

  double dt=((nFrames<1)? 0.0 : 2.0*3.141592/nFrames);

  double t=this->Frame*dt;
  double r=this->CamRadius->text().toDouble();
  double h=this->CamHeight->text().toDouble();

  double focX=this->FocalX->text().toDouble();
  double focY=this->FocalY->text().toDouble();
  double focZ=this->FocalZ->text().toDouble();

  double camX=r*cos(t);
  double camY=r*sin(t);
  double camZ=h;

  double camTX=-r*sin(t);
  double camTY=r*cos(t);

  double camUpX=-camTY*camZ;
  double camUpY=camTX*camZ;
  double camUpZ=-camTX*camY+camTY*camX;

  camX+=focX;
  camY+=focY;
  camZ+=focZ;

  pqRenderView *l_view=dynamic_cast<pqRenderView*>(this->view());
  if (!l_view)
    {
    sqErrorMacro(qDebug(),"Failed to get the current view.");
    return;
    }

  vtkSMRenderViewProxy *l_proxy=l_view->getRenderViewProxy();

  vtkSMDoubleVectorProperty *prop;

  double pos[3]={camX,camY,camZ};
  prop=dynamic_cast<vtkSMDoubleVectorProperty*>(l_proxy->GetProperty("CameraPosition"));
  prop->SetElements(pos);

  double cen[3]={focX,focY,focZ};
  prop=dynamic_cast<vtkSMDoubleVectorProperty*>(l_proxy->GetProperty("CameraFocalPoint"));
  prop->SetElements(cen);

  double up[3]={camUpX,camUpY,camUpZ};
  prop=dynamic_cast<vtkSMDoubleVectorProperty*>(l_proxy->GetProperty("CameraViewUp"));
  prop->SetElements(up);

  prop=dynamic_cast<vtkSMDoubleVectorProperty*>(l_proxy->GetProperty("CenterOfRotation"));
  prop->SetElements(cen);

  l_proxy->UpdateVTKObjects();

  l_view->render();
}

//-----------------------------------------------------------------------------
void pqSC11DemoReader::accept()
{
  #if defined pqSC11DemoReaderDEBUG
  cerr << ":::::::::::::::::::::::::::::::accept" << endl;
  #endif

  this->pqAutoGeneratedObjectPanel::accept();
  this->pqNamedObjectPanel::accept();

  vtkSMProxy* pmProxy=this->referenceProxy()->getProxy();

  vtkSMIntVectorProperty *dviProp
    = dynamic_cast<vtkSMIntVectorProperty*>(pmProxy->GetProperty("DirtyValueInfo"));
  pmProxy->UpdatePropertyInformation(dviProp);
  int dv=dviProp->GetElement(0);

  dv=(dv==0?1:0);

  vtkSMIntVectorProperty *dvProp
    = dynamic_cast<vtkSMIntVectorProperty*>(pmProxy->GetProperty("DirtyValue"));
  dvProp->SetElement(0,dv);
  dvProp->Modified();

  pmProxy->UpdateVTKObjects();

}

